# Generated by Django 4.0.3 on 2022-04-17 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catigory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catigory_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_title', models.CharField(max_length=64)),
                ('lot_img', models.ImageField(blank=True, upload_to='pic/')),
                ('lot_description', models.TextField(blank=True)),
                ('lot_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_status', models.BooleanField(default=True)),
                ('lot_catigory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.catigory')),
                ('lot_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
