# Generated by Django 4.0.3 on 2022-04-27 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_catigory_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='catigory_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_img',
            field=models.ImageField(blank=True, upload_to='pic/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_price',
            field=models.DecimalField(decimal_places=2, help_text='Min prise is $0.01', max_digits=20, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Title'),
        ),
    ]
