# Generated by Django 4.0.3 on 2022-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_catigory_catigory_name_alter_lot_lot_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_img',
            field=models.ImageField(blank=True, default='media/pic/no_img.jpg', upload_to='pic/', verbose_name='Photo'),
        ),
    ]
