# Generated by Django 4.0.3 on 2022-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_lot_lot_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_img',
            field=models.ImageField(blank=True, default='pic/no_img.jpg', upload_to='pic/', verbose_name='Photo'),
        ),
    ]
