# Generated by Django 4.0.3 on 2022-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_lot_lot_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_user_name', models.CharField(max_length=100)),
                ('comment_data_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
