# Generated by Django 4.0.3 on 2022-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
