# Generated by Django 4.0.3 on 2022-04-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_comment_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
