# Generated by Django 4.0.3 on 2022-04-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_user_name', models.CharField(blank=True, max_length=100)),
                ('comment_data_create', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.lot')),
            ],
        ),
    ]
